### PR TITLE
Setup client-side authentication

### PR DESCRIPTION
**Pull request by anand-yadav55**
Firebase, React setup

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Hey @anand-yadav55 
We would prefer to keep this repo just the API, will give you access to the front-end repo now. Can you send there?
Will be super awesome

**Comment by DesignrKnight** [comment]
https://github.com/dscnitrourkela/project-guava-web

Will be awesome if you send PR here

**Comment by DesignrKnight** [comment]
Apologies on not clarifying earlier

**Comment by anand-yadav55** [comment]
Sure, no problem

**Pull request closed without merging**
